### ISSUE TITLE
Version check for MPI installation

### ISSUE THREAD

**Issue by AndreasNygaard** [AarhusCosmology/connect_public#13]
Right now `mpirun` is used with the flag `--oversubscribe` but this only works for OpenMPI v3.x and above. For older versions, oversubscription is allowed by default. Other MPI installations, such as MPICH, does not recognise the flag either, so a check for other installations would be good too.

**Comment by jmd-dk** [comment]
This is quite a nasty problem in practice, as no unified system for checking the MPI distribution/version exists. You can check [this](https://github.com/jmd-dk/concept/blob/master/concept#L413-L533) out for how it's done in CO*N*CEPT. In particular, it's safer to set the environment variable
```bash
export OMPI_MCA_rmaps_base_oversubscribe=1
```
rather than supplying `--oversubscribe`.

**Comment by AndreasNygaard** [comment]
Wow, thanks! I have never seen this environment variable before, but it might be just what I need.
I actually only need to know when and when not to use `--oversubscribe` so what I ended up with was just a check for only OpenMPI v3.x or above. However, if the environment variable works regardless of the MPI distribution, then I probably don't need to check for it at all. I presume that it works with both MPICH and older versions of OpenMPI even though oversubscription is allowed by default in these?

**Comment by jmd-dk** [comment]
It's safe to always just add this environment variable. For MPI versions that are aware of it, it does it's thing. For MPI versions that are not, nothing happens, but these coincide with the versions for which oversubscription is allowed by default (at least to a good approximation, some obscure MPI implementation out there probably behave differently).
