### ISSUE TITLE
More visible std output from iterative data generation

### ISSUE THREAD

**Issue by EBHolm** [AarhusCosmology/connect_public#19]
When creating data using the iterative algorithm, the standard output from MontePython is put in a `/chain/connect_out` subfolder of the `montepython_public` folder specified by the user in the parameter file. This output is very useful for debugging and other purposes. It is not stated anywhere in the documentation that the output is put there, and it would be more straightforward to instead put the output in an `out` subfolder of CONNECT (rather than MontePython), since otherwise the user might never discover the output files.

**Comment by AndreasNygaard** [comment]
This could be useful to make more accessible to the user. I think it might be good to put a `montepython.log` in each iteration folder. I think I can work on this in a few days.
