### ISSUE TITLE
Ability to set cosmological likelihoods for iterative sampling manually

### ISSUE THREAD

**Issue by EBHolm** [AarhusCosmology/connect_public#21]
It would be nice if it was possible to manually define which likelihoods the iterative training procedure should use in the parameter file, if one wants to taylor specifically to the likelihoods one wants to use. Maybe this is already possible?

**Comment by AndreasNygaard** [comment]
This is not possible yet, but it will be soon with the next update (also featuring a Cobaya implantation).
