### ISSUE TITLE
Non-hierarchical calling of CLASS module in disguised_classy

### ISSUE THREAD

**Issue by EBHolm** [AarhusCosmology/connect_public#24]
The Python wrapper for CLASS++ computes the CLASS modules hierarchically, only calling the modules required for the specifically requested computation (e.g. if `.get_background()` is called, only the background is computed). Thus, one can evaluate background-only likelihoods such as BAO easily since the wrapper will compute the backgrounds with CLASS without spending time on e.g. perturbation computations.

The class_public wrapper does not have this hierarchical evaluation feature, and it is therefore not possible to compute background quantities directly without also computing perturbation quantities. In effect, it is not clear how to compute background-only likelihoods with CONNECT using class_public. 

The solution is either to emulate the background quantities (this is quite nontrivial however, since most of them compute values at grids in several dimensions) or to somehow modify the disguised classy wrapper to overwrite the computation functions in order to implement the hierarchical evaluation.

**Comment by EBHolm** [comment]
I will look into this issue, so @AndreasNygaard, you can assign me this issue (I cannot self-assign since I do not have the correct GitHub permissions).

**Comment by AndreasNygaard** [comment]
This has already been fixed. One can compute class_public to a specific level using the “level” keyword. This has been implemented and should work. I will mark the issue as closed for now.

**Comment by EBHolm** [comment]
Very nice, good job!

How does the `level` keyword work?

**Comment by AndreasNygaard** [comment]
The level could be `background` or `lensing` etc., and it is called as `cosmo.compute(level=[‘background’])`, where `background` could be replaced with any level of computation.
