### ISSUE TITLE
Check whether an iteration folder is complete when resuming iterations

### ISSUE THREAD

**Issue by gplynch619** [AarhusCosmology/connect_public#27]
Wasn't sure how to phrase this in the title, but I will explain here. I think it would be beneficial to check whether an iteration folder (i.e. `number_3`) corresponds to a completed iteration vs a partially completed one when deciding from where to resume iterations. Currently, connect decides this by finding the highest `number_x` folder, and moving back one folder to retrain and restart the iterations. This works fine if the previous execution was stopped midway through an iteration, but this is not always the case leading to someone resuming iterations. 

For example, when resuming iterations after a halted MCMC it can be the case that the initial retraining of the neural network fails due to NaN losses, causing execution to stop. If the user simply runs connect again, the effect will be to delete the highest `number_x` folder, despite the fact that this folder does not actually correspond to an interrupted MCMC and instead has fully completed chains and computed spectra. This effect I believe is unintended, and can be remedied by adding a check for `training.log` in the iteration folder before deleting.

**Comment by AndreasNygaard** [comment]
Thanks for letting me know. I will add some kind of check as you suggested, but it probably also has to check for NaN values in `training.log`. I will do this in a upcoming update.

**Comment by AndreasNygaard** [comment]
resolved by #33
